#include <iostream>
#include <numeric>
#include "LoadBalancer.cpp"
using namespace std; 

/// @brief THIS FUNCTION WAS GENERATED BY CHATGPT: A function to randomly generate true or false
/// @return True or False
bool getRandomBool() {
  return rand() % 2 == 0;
}

int main(){
    srand(time(0));
    int numWebServers; 
    cout << "Enter the number of desired servers: "; 
    cin >> numWebServers; 
    int totalClockCycles; 
    cout << "Enter the desired number of clock cycles: "; 
    cin >> totalClockCycles; 
    // set up the LoadBalancer with the appropriate number of web servers, total clock cycles, and a full queue
    LoadBalancer loadBalancer(totalClockCycles); 
    for(int i = 0; i < numWebServers; i++) loadBalancer.webServers.push_back(WebServer()); 
    for(int i = 0; i < numWebServers * 20; i++) loadBalancer.queue.push(Request(2, 500)); 
    loadBalancer.numRequestsReceived = loadBalancer.queue.size(); 
    while(!loadBalancer.queue.empty() && loadBalancer.currClockCycle <= loadBalancer.maxClockCycles){
        loadBalancer.currClockCycle += 2; 
        // have the load balancer send all requests to available webservers
        loadBalancer.sendToWebserver();
        // check to see if any requests have finished
        for(int i = 0; i < loadBalancer.webServers.size(); i++) loadBalancer.webServers.at(i).replyToClient(loadBalancer.currClockCycle, i + 1); 
        // check to see if any new requests have arrived
        for(int i = 0; i < 5; i++){
            if (getRandomBool()){ // randomly choose if a new element should be added
                loadBalancer.queue.push(Request(2, 500));
                loadBalancer.numRequestsReceived += 1; 
            }
        }
    }
}